[variables]
NIXPACKS_NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "python3"]

[phases.install]
cmds = ["cd svelte-app && npm ci"]

[phases.build]
cmds = ["cd svelte-app && npm run build"]

[start]
cmd = "cd svelte-app && node build"
