[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = ["cd svelte-app && npm ci"]

[phases.build]
cmds = ["cd svelte-app && npm run build"]

[start]
cmd = "cd svelte-app && node build"
