[build]
builder = "nixpacks"
watchPatterns = ["svelte-app/**"]

[deploy]
startCommand = "cd svelte-app && node build"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
